import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en': {
          'queue': 'Queue',
          'waiting': 'Waiting',
          'new_queue': 'New Queue',
          'call': 'Call',
          'recall': 'Recall',
          'day': "day's",
          'hour': 'hours',
          'minute': 'minutes',
          'served': 'Served',
          'void': 'Void',
          'all': 'All',
          'calling': 'Calling',
          'last_call': 'Last Call',
          'cancelled': 'Cancelled',
          'expired': 'Expired',
          'all_queue': 'All Queues',
          'created_at': 'Created At',
          'search_queue': 'Search Queue Number',
          'call_count': 'Call Count',
          'reprint': 'Reprint',
          'syncronize': 'Synchronize',
          'customer_screen': 'Customer Screen',
          'shift': 'Shift',
          'close_customer_screen': 'Close Customer Screen',
          'printer_setting': 'Printer Setting',
          'config': 'Configuration',
          'help': 'Help & Documentation',
          'creating': 'Creating',
          'rto_title': 'Request Timed Out (s)',
          'unauthorized_title': 'Unauthorized',
          'bad_gateway_title': 'Bad Gateway',
          'too_many_request_title': 'Server Hit a Snag',
          'rto_desc': 'Something went wrong. Please try again.',
          'unauthorized_desc': 'You are not authorized to access this page.',
          'bad_gateway_desc': 'Please Wait a Moment adn Try Again',
          'too_many_request_desc': 'Too Many Request. Please Try Again Later.',
          'forbidden_title': 'Shift Not Found!',
          'forbidden_desc': 'Try to create a new shift',
          'server_error_title': 'Server Error',
          'server_error_desc':
              'There is a problem with the server. Please try again later or contact the administrator.',
          'succeed_send_data': 'Sent to live server',
          'failed_send_data': 'Failed to send data',
          'failed_sync_data': 'Failed to sync data',
          'succeed_sync_data': 'Success to sync data',
          'version': 'Version',
          'withhold_queue': 'Withhold Queue Number',
          'close': 'Close',
          'withhold': 'Withhold',
          'unable_to_load': 'Unable to load data',
          'try_again': 'Try Again',
          'no_data': 'No Data',
          'served_queue': 'Served Queue',
          'served_queue_desc': 'Are you sure you want to serve this queue?',
          'void_queue': 'Void Queue',
          'void_queue_desc': 'Are you sure you want to void this queue?',
          'input_url': 'URL server cannot be empty',
          'input_key': 'License key cannot be empty',
          'input_rto': 'Request Time Out cannot be empty',
          'empty_input': 'Field cannot be empty',
          'submit': 'Submit',
          'env': 'Environment',
          'base_url': 'Base URL',
          'exm': 'exm',
          'save_config': 'Save',
          'title_call_queue_text': 'Title Call Queue Text',
          'instruction_call_queue_text': 'Instruction Call Queue Text',
          'queue_number': 'Queue Number',
          'exm_instruction': 'Please confim to the greeter',
          'video_config': 'Video',
          'timer_fulscreen': 'Auto Fullscreen After Inactivity',
          'hint_timer_fulscreen': 'Select fullscreen ads timer',
          'muted_video': 'Muted',
          'more_config': 'Others',
          'cron_run': 'Timed-based Job Scheduler (CRON)',
          'connect': 'Connect',
          'disconnect': 'Disconnect',
          'type_printer': 'Type Printer Device',
          'reconnect': 'Reconnect',
          'test_print': 'Test Print',
          'new_shift': 'New Shift',
          'end_shift': 'End Shift',
          'queue_config': 'Queue Configuration',
          'queue_count': 'Queue Count',
          'call_delay': 'Call Delay',
          'call_repeat': 'Call Repeat',
          'play_video': 'Play Video',
          'times': 'Times',
          'seconds': 'Seconds',
          'play_video_desc': 'Yes, play all available videos',
          'play_video_desc_no': 'No, do not play any videos',
          'closed_shift': 'Closed Shift',
          'recaps': 'Recaps',
          'quantity': 'Quantity',
          'quit_message': 'Are you sure you want to quit?',
          'yes': 'Yes',
          'no': 'No',
          'forget_end_shift':
              "Don't forget to end the shift. Would you like to end it now?",
          'success_create': 'created successfully',
          'failed': 'Failed!',
          'unable_to_create_queue': 'Unable to create queue. Please try again',
          'unable_to_print_queue': 'Unable to print queue. Please try again',
          'update_serve': 'Status updated successfully to served',
          'update_void': 'Status updated successfully to void',
          'update_qty': 'Queue quantity updated successfully to',
          'called': 'called successfully',
          'failed_serve': 'Unable update status Served!. Please try again',
          'failed_void': 'Unable update status Void!. Please try again',
          'failed_qty': 'Unable update queue quantity. Please try again',
          'no_queue': 'no queue',
          'canceled_queue': 'This queue has been canceled by the customer',
          'failed_call': 'Failed to call queue. Please try again',
          'too_much_number': 'Too much number!',
          'too_much_number_desc': 'The number is too long to call!',
          'sure_to_serve':
              'Are you sure you want to update this queue to served?',
          'sure_to_void': 'Are you sure you want to update this queue to void?',
          'failed_register_key': 'Failed to register license key!',
          'failed_register_key_desc': 'Please input the correct license key',
          'success': 'Success!',
          'environment_updated': 'Environment has been updated!',
          'invalid_license_key': 'Invalid license key!',
          'invalid_license_key_desc': 'Please enter a valid license key.',
          'not_found': 'Not Found!',
          'server_not_found': 'Server not found',
          'thank_you': 'Thank You for your patience!',
          'printed_at': 'Printed At:',
          'start_shift': 'Start Shift',
          'end_shift_at': 'End Shift',
          'shift_overview': 'Shift Overview',
          'count': 'Count',
          'printer_error': 'Printer Error!',
          'printer_error_desc':
              'Printer is not selected. Please select a printer first in the printer setting.',
          'new_shift_desc': 'New shift has been created',
          'failed_create_shift': 'Unable to create new shift. Please try again',
          'sure_end_shift': 'Are you sure you want to end this shift?',
          'sure_new_shift': 'Are you sure you want to create a new shift?',
          'success_end_shift': 'Shift has been ended!',
          'failed_end_shift': 'Unable to end shift. Please try again',
          'failed_active_queue_end_shift':
              'Unable to end shift. There is one or few active queues',
          'cancel': 'Cancel',
          'open_new_shift_now': 'Open New Shift Now',
          'in_a_second': 'In a second',
          'the_server_may_not_be_active': 'The server may not be active',
          'continue_to_experience_issues':
              'If you continue to experience issues',
          'contact_administrator':
              'Please contact the administrator for further assistance',
          'not_now': 'Not Now',
          'in_seconds': 'In Seconds',
          'path': 'Folderpath',
          'auto_fullscreen': 'Auto Fullscreen',
          'all_rights_reserved': 'All Rights Reserved.',
          'video_downloaded': 'Video has been downloaded',
          'failed_download_video': 'Failed to download video',
          'file_already_exists': 'File already exists at ',
          'connection': 'Connection',
          'license_key': 'License Key',
          'language': 'Language',
          'choose_language': ' Screen Display',
          'language_print': 'Paper Printout',
          'show_qr_print': 'Show QR Code on Printout',
        },
        'id': {
          'queue': 'Antrean',
          'waiting': 'Menunggu',
          'new_queue': 'Tambah Antrean',
          'call': 'Panggil',
          'day': 'hari',
          'hour': 'jam',
          'minute': 'menit',
          'served': 'Dilayani',
          'void': 'Dibatalkan',
          'all': 'Semua',
          'calling': 'Memanggil',
          'recall': 'Panggil Ulang',
          'last_call': 'Panggilan Terakhir',
          'cancelled': 'Batal',
          'expired': 'Kedaluwarsa',
          'all_queue': 'Semua Antrean',
          'created_at': 'Dibuat Pada',
          'queue_number': 'Nomor Antrean',
          'search_queue': 'Cari Nomor Antrean',
          'call_count': 'Jumlah Panggilan',
          'reprint': 'Cetak Ulang',
          'syncronize': 'Sinkronisasi',
          'customer_screen': 'Layar Pelanggan',
          'close_customer_screen': 'Tutup Layar Pelanggan',
          'shift': 'Shift',
          'printer_setting': 'Pengaturan Printer',
          'config': 'Konfigurasi',
          'unauthorized_desc': 'Anda tidak diizinkan mengakses halaman ini.',
          'help': 'Bantuan & Dokumentasi',
          'creating': 'Membuat',
          'rto_title': 'Waktu Permintaan Habis',
          'unauthorized_title': 'Tidak Diizinkan',
          'bad_gateway_title': 'Kesalahan Gateway',
          'too_many_request_title': 'Server Terlampau Sibuk',
          'forbidden_title': 'Shift Tidak Ditemukan!',
          'forbidden_desc': 'Membuat shift baru',
          'server_error_title': 'Kesalahan Server',
          'server_error_desc':
              'Ada masalah dengan server. Silakan coba lagi nanti atau hubungi administrator.',
          'succeed_send_data': 'Terkirim ke live server',
          'failed_send_data': 'Gagal mengirim data',
          'failed_sync_data': 'Gagal mengsinkronkan data',
          'succeed_sync_data': 'Berhasil mengsinkronkan data',
          'version': 'Versi',
          'withhold_queue': 'Antrean yang ditahan',
          'close': 'Tutup',
          'withhold': 'Antrean ditahan',
          'unable_to_load': 'Tidak dapat memuat data',
          'try_again': 'Coba Lagi',
          'no_data': 'Tidak Ada Data',
          'served_queue': 'Menyelesaikan Antrean',
          'served_queue_desc': 'Apakah Anda yakin antrean ini sudah dilayani?',
          'void_queue': 'Membatalkan Antrean',
          'void_queue_desc': 'Apakah Anda yakin ingin membatalkan antrean ini?',
          'input_url': 'URL server tidak boleh kosong',
          'input_key': 'License key tidak boleh kosong',
          'input_rto': 'Request Time Out tidak boleh kosong',
          'empty_input': 'Field tidak boleh kosong',
          'submit': 'Kirim',
          'env': 'Setting',
          'base_url': 'URL Utama',
          'exm': 'cth',
          'save_config': 'Simpan',
          'title_call_queue_text': 'Judul Panggil Antrean Teks',
          'instruction_call_queue_text': 'Instruksi Panggil Antrean Teks',
          'exm_instruction': 'Silahkan konfirmasi ke greeter',
          'video_config': 'Video',
          'timer_fulscreen': 'Waktu Jeda Layar Penuh',
          'hint_timer_fulscreen': 'Pilih timer iklan fullscreen',
          'muted_video': 'Bisukan',
          'more_config': 'Lainnya',
          'cron_run': 'Penjadwalan Pengiriman Data (CRON)',
          'connect': 'Hubungkan',
          'disconnect': 'Putuskan',
          'type_printer': 'Jenis Perangkat Printer',
          'reconnect': 'Hubungkan Kembali',
          'test_print': 'Coba Cetak',
          'new_shift': 'Shift Baru',
          'end_shift': 'Akhiri Shift',
          'queue_config': 'Konfigurasi Antrean',
          'queue_count': 'Jumlah Antrean',
          'call_delay': 'Delay Panggilan',
          'call_repeat': 'Ulangi Panggilan',
          'play_video': 'Putar Video',
          'times': 'Kali',
          'seconds': 'Detik',
          'play_video_desc': 'Ya, putar semua video yang tersedia',
          'play_video_desc_no': 'Tidak, jangan putar video apapun',
          'closed_shift': 'Shift Ditutup',
          'recaps': 'Ringkasan',
          'quantity': 'Jumlah',
          'quit_message': 'Apakah Anda yakin ingin keluar?',
          'yes': 'Ya',
          'no': 'Tidak',
          'forget_end_shift':
              "Jangan lupa untuk mengakhiri shift. Apakah Anda ingin mengakhirinya sekarang?",
          'success_create': 'berhasil dibuat',
          'failed': 'Ada Kesalahan!',
          'unable_to_create_queue':
              'Tidak dapat membuat antrean. Silakan coba lagi',
          'unable_to_print_queue':
              'Tidak dapat mencetak antrean. Silakan coba lagi',
          'update_serve': 'Status berhasil diperbarui menjadi Dilayani',
          'update_void': 'Status berhasil diperbarui menjadi Batal',
          'update_qty': 'Jumlah antrean berhasil diperbarui',
          'called': 'berhasil dipanggil',
          'failed_serve':
              'Tidak dapat memperbarui status menjadi "Dilayani". Silakan coba lagi',
          'failed_void':
              'Tidak dapat memperbarui status menjadi "Batal". Silakan coba lagi',
          'failed_qty':
              'Tidak dapat memperbarui jumlah antrean. Silakan coba lagi',
          'no_queue': 'tidak ada antrean',
          'canceled_queue': 'Antrean ini telah dibatalkan oleh pelanggan',
          'failed_call': 'Gagal memanggil antrean. Silakan coba lagi',
          'too_much_number': 'Terlalu banyak angka!',
          'too_much_number_desc':
              'Limit angka terlalu panjang untuk dipanggil!',
          'sure_to_serve':
              'Apakah Anda yakin ingin memperbarui Antrean ini menjadi dilayani?',
          'sure_to_void':
              'Apakah Anda yakin ingin memperbarui antrean ini menjadi batal?',
          'failed_register_key': 'Gagal mendaftarkan license key!',
          'failed_register_key_desc': 'Silakan masukkan license key yang benar',
          'success': 'Berhasil!',
          'environment_updated': 'Env telah diperbarui!',
          'invalid_license_key': 'License key tidak valid!',
          'invalid_license_key_desc':
              'Silakan masukkan license key yang valid.',
          'not_found': 'Tidak Ditemeukan!',
          'server_not_found': 'Server tidak ditemukan',
          'printed_at': 'Dicetak Pada:',
          'start_shift': 'Mulai Shift',
          'end_shift_at': 'Shift Berakhir',
          'shift_overview': 'Rekap Shift',
          'failed_active_queue_end_shift':
              'Tidak dapat mengakhiri shift. Ada satu atau beberapa antrean aktif',
          'count': 'Jumlah',
          'printer_error': 'Printer Error!',
          'printer_error_desc':
              'Printer belum dipilih. Silakan pilih printer terlebih dahulu di pengaturan printer.',
          'new_shift_desc': 'Shift baru telah dibuat',
          'failed_create_shift':
              'Tidak dapat membuat shift baru. Silakan coba lagi',
          'sure_end_shift': 'Apakah Anda yakin ingin mengakhiri shift ini?',
          'sure_new_shift': 'Apakah Anda yakin ingin membuat shift baru?',
          'success_end_shift': 'Shift telah berakhir!',
          'cancel': 'Batal',
          'open_new_shift_now': 'Buka Shift Baru Sekarang',
          'in_a_second': 'Tunggu sebentar',
          'the_server_may_not_be_active': 'Server mungkin tidak aktif',
          'continue_to_experience_issues': 'Jika Anda terus mengalami masalah',
          'contact_administrator':
              'Silakan hubungi administrator untuk bantuan lebih lanjut',
          'not_now': 'Nanti',
          'in_seconds': 'Dalam Detik',
          'path': 'Path Folder',
          'rto_desc' : 'Ada yang salah. Silakan coba lagi.',
          'auto_fullscreen': 'Otomasi Layar Penuh',
          'all_rights_reserved': 'Hak Cipta Dilindungi UU.',
          'video_downloaded': 'Video telah diunduh',
          'failed_download_video': 'Gagal mengunduh video',
          'file_already_exists': 'File sudah ada di ',
          'connection': 'Koneksi',
          'license_key': 'Kode Lisensi',
          'language': 'Bahasa',
          'choose_language': 'Tampilan Layar',
          'language_print': 'Cetakan Kertas',
          'show_qr_print': 'Tampilkan Kode QR pada Cetakan',
        }
      };
}
